local smart_paste = require("smart-paste")

describe("smart-paste", function()
	it("works!", function()
		local reader = require("reader")
		local format, content, err = reader.read()
		assert(type(format) == "string", err)
		assert(type(content) == "string", err)
	end)
end)
